"""
Basic usage example for MemoBot SDK.

This example shows how to:
1. Initialize the client
2. Log events (speech, vision, actions)
3. Search memory
4. Ask questions
5. Get user profiles
"""
from sdk import MemoBotClient
from datetime import datetime
import time


def main():
    # Initialize client
    client = MemoBotClient(
        api_url="http://localhost:8000",
        api_key="demo-api-key-123"
    )
    
    robot_id = "robot-demo-001"
    user_id = "user-alice"
    
    print("=" * 60)
    print("MemoBot SDK - Basic Usage Example")
    print("=" * 60)
    
    # 1. Log speech events
    print("\n1. Logging speech events...")
    
    events = [
        "I don't like loud noises.",
        "Could I have tea instead of coffee?",
        "The living room is too bright.",
        "I prefer the temperature around 72 degrees."
    ]
    
    for text in events:
        result = client.log_speech(
            robot_id=robot_id,
            text=text,
            speaker="user",
            user_id=user_id,
            location="living_room"
        )
        print(f"  ✓ Logged: '{text[:50]}...' [ID: {result['event_id']}]")
        time.sleep(0.5)  # Small delay to ensure different timestamps
    
    # Log robot responses
    robot_responses = [
        "I understand you prefer a quieter environment.",
        "I'll remember you prefer tea.",
    ]
    
    for text in robot_responses:
        result = client.log_speech(
            robot_id=robot_id,
            text=text,
            speaker="robot",
            user_id=user_id,
            location="living_room"
        )
        print(f"  ✓ Robot said: '{text}'")
        time.sleep(0.5)
    
    # 2. Log vision event
    print("\n2. Logging vision event...")
    
    result = client.log_vision(
        robot_id=robot_id,
        description="Detected user in living room, appears relaxed",
        objects=["person", "couch", "lamp"],
        location="living_room"
    )
    print(f"  ✓ Vision event logged [ID: {result['event_id']}]")
    
    # 3. Log action
    print("\n3. Logging robot action...")
    
    result = client.log_action(
        robot_id=robot_id,
        action="ADJUSTED_LIGHTS",
        description="Dimmed living room lights to 60%",
        metadata={"location": "living_room", "brightness": 60}
    )
    print(f"  ✓ Action logged [ID: {result['event_id']}]")
    
    # Give some time for embeddings to be generated
    print("\n  (Waiting 2 seconds for event processing...)")
    time.sleep(2)
    
    # 4. Search memory
    print("\n4. Searching memory...")
    
    search_result = client.search_memory(
        robot_id=robot_id,
        user_id=user_id,
        query="What are the user's preferences about noise and drinks?",
        limit=5
    )
    
    print(f"  Found {len(search_result['items'])} relevant events:")
    for item in search_result['items'][:3]:
        print(f"    - [{item['timestamp']}] {item['type']}: {item['text']}")
        print(f"      Score: {item['score']:.3f}")
    
    # 5. Ask a question
    print("\n5. Asking memory a question...")
    
    answer_result = client.ask_memory(
        robot_id=robot_id,
        user_id=user_id,
        question="What are Alice's preferences about noise, drinks, and temperature?"
    )
    
    print(f"\n  Question: What are Alice's preferences?")
    print(f"  Answer: {answer_result['answer']}")
    print(f"  Confidence: {answer_result['confidence']:.2f}")
    print(f"\n  Supporting events:")
    for event in answer_result['supporting_events']:
        print(f"    - {event['text']}")
    
    # 6. Get user profile
    print("\n6. Getting user profile...")
    
    try:
        profile = client.get_profile(
            robot_id=robot_id,
            entity_type="user",
            entity_id=user_id
        )
        
        print(f"\n  Profile for {user_id}:")
        print(f"  Summary: {profile['summary']}")
        
        if profile['facts']:
            print(f"  Facts:")
            for fact in profile['facts']:
                print(f"    - {fact['subject']} {fact['predicate']} {fact['object']} "
                      f"(confidence: {fact['confidence']:.2f})")
    except Exception as e:
        print(f"  Profile not yet available: {e}")
        print("  (Profiles are generated by background workers)")
    
    print("\n" + "=" * 60)
    print("Example completed successfully!")
    print("=" * 60)


if __name__ == "__main__":
    main()

